#ifndef ORCA_PRESENTER_TEST_BUDGETCONTROLLER_STUB_HPP
#define ORCA_PRESENTER_TEST_BUDGETCONTROLLER_STUB_HPP

#include "../common.hpp"
#include "EstimateControllerStub.hpp"

#endif // ORCA_PRESENTER_TEST_BUDGETCONTROLLER_STUB_HPP
