//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef WXCRAFTER_BASE_CLASSES_H
#define WXCRAFTER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/filepicker.h>
#include <wx/datectrl.h>
#include <wx/button.h>
#include <wx/gbsizer.h>
#include <wx/textctrl.h>
#include <wx/grid.h>
#include <wx/htmllbox.h>
#include <wx/frame.h>
#include <wx/menu.h>
#include <wx/statusbr.h>
#include <wx/panel.h>
#include <wx/choice.h>
#include <wx/arrstr.h>
#include <wx/checkbox.h>
#include <wx/spinctrl.h>
#include <wx/checklst.h>
#include <wx/statline.h>

class CreateDatabaseDialogBase : public wxDialog
{
protected:
    wxStaticText* lbLocation;
    wxFilePickerCtrl* flLocation;
    wxStaticText* lbStart;
    wxDatePickerCtrl* dtStart;
    wxStdDialogButtonSizer* m_stdBtnSizer17;
    wxButton* btOk;
    wxButton* btCancel;

protected:

public:
    CreateDatabaseDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Setup Database"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~CreateDatabaseDialogBase();
};


class ExecutionDialogBase : public wxDialog
{
protected:
    wxStaticText* lbBudget;
    wxTextCtrl* txBudget;
    wxTextCtrl* txEstimateName;
    wxStaticText* lbEstimated;
    wxTextCtrl* txEstimateAmount;
    wxStaticText* lbAccounted;
    wxStaticText* lbLeftover;
    wxTextCtrl* txAccounted;
    wxTextCtrl* txLeftover;
    wxStaticText* lbExecutions;
    wxGrid* gdExecutions;
    wxButton* btAdd;
    wxButton* btDelete;
    wxButton* btClose;
    wxStaticText* lbEstimateName;

protected:
    virtual void OngdExecutionsCellChange(wxGridEvent& event) { event.Skip(); }
    virtual void OnbtAddClick(wxCommandEvent& event) { event.Skip(); }
    virtual void OnbtDeleteClick(wxCommandEvent& event) { event.Skip(); }

public:
    ExecutionDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Execution"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(600,-1), long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);
    virtual ~ExecutionDialogBase();
};


class WalletOverviewDialogBase : public wxDialog
{
protected:
    wxSimpleHtmlListBox* lsWallets;
    wxStaticText* lbName;
    wxTextCtrl* txName;
    wxStaticText* lbObs;
    wxTextCtrl* txObs;
    wxButton* btEdit;
    wxButton* btAdd;
    wxButton* btRemove;
    wxButton* btClose;

protected:
    virtual void OnLswalletsListbox(wxCommandEvent& event) { event.Skip(); }
    virtual void OnTxnameTextUpdated(wxCommandEvent& event) { event.Skip(); }
    virtual void OnTxobsTextUpdated(wxCommandEvent& event) { event.Skip(); }
    virtual void OnBteditButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnBtaddButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnBtremoveButtonClicked(wxCommandEvent& event) { event.Skip(); }

public:
    WalletOverviewDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Wallet Overview"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~WalletOverviewDialogBase();
};


class OrcamentoMainFrameBase : public wxFrame
{
protected:
    wxMenuBar* mnMain;
    wxMenu* mnFile;
    wxMenuItem* mnFileNew;
    wxMenuItem* mnFileOpen;
    wxMenuItem* mnFileSave;
    wxMenuItem* mnFileSaveAs;
    wxMenuItem* mnFileSeparator;
    wxMenuItem* mnFileQuit;
    wxMenu* mnBudget;
    wxMenuItem* mnBudgetCreateNext;
    wxMenuItem* mnBudgetExecuteNext;
    wxMenuItem* mnBudgetSeparator;
    wxMenuItem* mnBudgetExport;
    wxMenu* mnEstimate;
    wxMenuItem* mnEstimateAdd;
    wxMenu* mnWallet;
    wxMenuItem* mnWalletOverview;
    wxMenu* mnHelp;
    wxMenuItem* mnHelpAbout;
    wxStatusBar* sbStatus;
    wxMenu* cmEstimate;
    wxMenuItem* cmEstimatesExecute;
    wxMenuItem* cmEstimatesCopySelectedRows;
    wxMenuItem* cmEstimatesSeparator;
    wxMenuItem* cmEstimatesDelete;
    wxSimpleHtmlListBox* lsMonths;
    wxGrid* gdEstimates;
    wxPanel* pnTotals;
    wxStaticText* lbTotalEstimated;
    wxTextCtrl* txTotalEstimated;
    wxStaticText* lbTotalAccounted;
    wxTextCtrl* txTotalAccounted;
    wxStaticText* lbTotalRemaining;
    wxTextCtrl* txTotalRemaining;
    wxButton* byFilterTotals;

protected:
    virtual void OnCloseWindow(wxCloseEvent& event) { event.Skip(); }
    virtual void OnMnfilenewMenuSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void OnMnfileopenMenuSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void OnMnfilesaveMenuSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void OnMnfilesaveasMenuSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void OnMnfilequitMenuSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void OnMnbudgetcreatenextMenuSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void OnMnbudgetexecutenextMenuSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void OnMnbudgetseparatorMenuSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void OnMnbudgetexportMenuSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void OnMnestimateaddMenuSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void OnMnwalletoverviewMenuSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void OnMnhelpaboutMenuSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void OnCmestimatesexecuteMenuSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void OnCmestimatescopyselectedrowsMenuSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void OnCmestimatesdeleteMenuSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void OnLsmonthsListbox(wxCommandEvent& event) { event.Skip(); }
    virtual void OnGdestimatesGridCellChanging(wxGridEvent& event) { event.Skip(); }
    virtual void OnGdestimatesGridCellLeftDclick(wxGridEvent& event) { event.Skip(); }
    virtual void OnGdestimatesGridCellRightClick(wxGridEvent& event) { event.Skip(); }
    virtual void OnByfiltertotalsButtonClicked(wxCommandEvent& event) { event.Skip(); }

public:
    OrcamentoMainFrameBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("OrcaMento"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(800,600), long style = wxDEFAULT_FRAME_STYLE);
    virtual ~OrcamentoMainFrameBase();
};


class BudgetFilterBase : public wxDialog
{
protected:
    wxStaticText* lbName;
    wxTextCtrl* txName;
    wxChoice* chName;
    wxCheckBox* ckInvertName;
    wxStaticText* lbDate;
    wxStaticText* lbDateFrom;
    wxSpinCtrl* spDateFrom;
    wxStaticText* lbDateTo;
    wxSpinCtrl* spDateTo;
    wxCheckBox* ckInvertDate;
    wxStaticText* lbEstimated;
    wxStaticText* lbEstimatedFrom;
    wxTextCtrl* txEstimatedFrom;
    wxStaticText* lbEstimateTo;
    wxTextCtrl* txEstimatedTo;
    wxCheckBox* ckinvertEstimated;
    wxStaticText* lbAccounted;
    wxStaticText* lbAccountedFrom;
    wxTextCtrl* txAccountedFrom;
    wxStaticText* lbAccountedTo;
    wxTextCtrl* txAccountedTo;
    wxCheckBox* ckInvertAccounted;
    wxStaticText* lbRemaining;
    wxStaticText* lbRemainingFrom;
    wxTextCtrl* txRemainingFrom;
    wxStaticText* lbRemainingTo;
    wxTextCtrl* txRemainingTo;
    wxCheckBox* ckInvertRemaining;
    wxStaticText* lbObservation;
    wxTextCtrl* txObservation;
    wxChoice* chObservation;
    wxCheckBox* ckInvertObservation;
    wxStaticText* lbCategories;
    wxCheckListBox* lsckCategories;
    wxCheckBox* ckInvertCategories;
    wxStaticText* lbWallets;
    wxCheckListBox* lsckWallets;
    wxCheckBox* ckInvertWallets;
    wxStaticLine* lnControls;
    wxButton* btReset;
    wxButton* btRefresh;
    wxButton* btClose;

protected:
    virtual void OnBtrefreshButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnBtcloseButtonClicked(wxCommandEvent& event) { event.Skip(); }

public:
    BudgetFilterBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Budget Filtering"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(600,500), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~BudgetFilterBase();
};

#endif
